package ct.migratordesktop.schema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import lombok.Setter;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

@Slf4j
class SchemaReCreator {
	@Setter
	private String	driverClassName	= "oracle.jdbc.driver.OracleDriver";
	private String	url;
	private String	sysUsername;
	private String	sysPassword;
	private String	username;
	private String	password;

	public SchemaReCreator( /* String[] args */ ) {
		//this.mainArgs = args;
		 
		 
		 
		 //final var xxx = new Person( sysUsername, driverClassName );
		
	}

	@SneakyThrows
	public Connection getConnection() {
		Class.forName( driverClassName );
		final Connection connection = DriverManager.getConnection( this.url, this.sysUsername, this.sysPassword );
		return connection;
	}

	//@SneakyThrows
	public void executeSql( String sql ) {
		//		//this.url = "jdbc:oracle:thin:@//localhost:1521/xe";
		//		this.password = this.mainArgs[2];//"Ora_Std_1522";

		final var lines0 = sql.lines().toList();
		this.url = lines0.get( 0 );
		this.sysUsername = lines0.get( 1 );
		this.sysPassword = lines0.get( 2 );
		this.username = lines0.get( 3 );
		this.password = lines0.get( 4 );

		final var lines = sql.lines()
			.skip( 5 )
			.filter( line -> !line.isBlank() ).filter( line -> !line.startsWith( "--" ) )
			.map( line -> line.replace( "×userName×", this.username ) )
			.map( line -> line.replace( "×password×", this.password ) )
			.toList();

		try (Connection connection = getConnection()) {
			//			if (this.url.contains( "localhost" ))
			//				disconnectSessions( connection );
			for ( String line : lines ) {
				try (Statement st = connection.createStatement()) {
					st.execute( line );
				}
				catch ( Exception e ) {
					log.atWarn().log( e.getCause().getMessage().trim() + " --> " + line );
				}
				finally {
					log.info( line );
				}
			}
			log.info("Ended");
		}
		catch ( Exception e ) {
			log.error( "Error in execute Sql {}", e.getCause() );
		}

	}

	//	private void disconnectSessions( Connection connection ) {
	//		final var query = "SELECT sid,serial# FROM v$session WHERE module like '%DBeaver%'".replace( "×userName×", this.mainArgs[3] );
	//
	//		try (PreparedStatement statement = connection.prepareStatement( query, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY )) {
	//			try (ResultSet resultSet = statement.executeQuery()) {
	//				while ( resultSet.next() ) {
	//					final var sid = resultSet.getString( "sid" );
	//					final var serial = resultSet.getString( "serial#" );
	//					//var killQuery = "ALTER SYSTEM KILL SESSION '"+sid+","+serial+"'";
	//					final var killQuery = "ALTER SYSTEM DISCONNECT SESSION '" + sid + "," + serial + "'";
	//					execute( connection, killQuery );
	//				}
	//			}
	//		}
	//		catch ( Exception e ) {
	//			log.atWarn().log( e.getCause().getMessage().trim() + " --> " + query );
	//		}
	//	}

//	private boolean execute( Connection connection, String sql ) {
//		try (Statement st = connection.createStatement()) {
//			return st.execute( sql );
//		}
//		catch ( Exception e ) {
//			log.atWarn().log( e.getCause().getMessage().trim() + " --> " + sql );
//		}
//		return false;
//	}

	public String getSql() {//@formatter:off
		return """
jdbc:oracle:thin:@localhost:1522:ORCLCDB
sys as sysdba
Ora_Std_1522
akkor
ct
----------------------------------------------------------------
alter session set "_ORACLE_SCRIPT"=true
drop user ×userName× CASCADE
CREATE USER ×userName× IDENTIFIED BY ×password× DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"

ALTER USER ×userName× QUOTA UNLIMITED ON "SYSTEM"
ALTER USER ×userName× QUOTA UNLIMITED ON "SYSAUX"
ALTER USER ×userName× QUOTA UNLIMITED ON "USERS"

GRANT "DBA" TO ×userName× WITH ADMIN OPTION
--GRANT "PPLB_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "DV_MONITOR" TO ×userName× WITH ADMIN OPTION
GRANT "CTXAPP" TO ×userName× WITH ADMIN OPTION
GRANT "DV_AUDIT_CLEANUP" TO ×userName× WITH ADMIN OPTION
GRANT "EM_EXPRESS_ALL" TO ×userName× WITH ADMIN OPTION
GRANT "WM_ADMIN_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "OLAP_USER" TO ×userName× WITH ADMIN OPTION
GRANT "OLAP_XS_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DV_SECANALYST" TO ×userName× WITH ADMIN OPTION
--GRANT "MAINTPLAN_APP" TO ×userName× WITH ADMIN OPTION
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO ×userName× WITH ADMIN OPTION
GRANT "XS_CACHE_ADMIN" TO ×userName× WITH ADMIN OPTION
--GRANT "AVTUNE_PKG_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "GDS_CATALOG_SELECT" TO ×userName× WITH ADMIN OPTION
GRANT "SCHEDULER_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "PROVISIONER" TO ×userName× WITH ADMIN OPTION
GRANT "AUDIT_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO ×userName× WITH ADMIN OPTION
GRANT "AQ_ADMINISTRATOR_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "SYSUMF_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "APPLICATION_TRACE_VIEWER" TO ×userName× WITH ADMIN OPTION
GRANT "XDB_WEBSERVICES" TO ×userName× WITH ADMIN OPTION
GRANT "LBAC_DBA" TO ×userName× WITH ADMIN OPTION
GRANT "OPTIMIZER_PROCESSING_RATE" TO ×userName× WITH ADMIN OPTION
GRANT "RECOVERY_CATALOG_USER" TO ×userName× WITH ADMIN OPTION
GRANT "DV_DATAPUMP_NETWORK_LINK" TO ×userName× WITH ADMIN OPTION
GRANT "GSMUSER_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "GATHER_SYSTEM_STATISTICS" TO ×userName× WITH ADMIN OPTION
GRANT "LOGSTDBY_ADMINISTRATOR" TO ×userName× WITH ADMIN OPTION
GRANT "DBJAVASCRIPT" TO ×userName× WITH ADMIN OPTION
GRANT "GSM_POOLADMIN_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "DV_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DV_POLICY_OWNER" TO ×userName× WITH ADMIN OPTION
GRANT "HS_ADMIN_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "XS_SESSION_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DV_GOLDENGATE_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "IMP_FULL_DATABASE" TO ×userName× WITH ADMIN OPTION
GRANT "DV_XSTREAM_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DV_PATCH_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "GGSYS_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO ×userName× WITH ADMIN OPTION
GRANT "EJBCLIENT" TO ×userName× WITH ADMIN OPTION
GRANT "HS_ADMIN_EXECUTE_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "JMXSERVER" TO ×userName× WITH ADMIN OPTION
GRANT "OLAP_DBA" TO ×userName× WITH ADMIN OPTION
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO ×userName× WITH ADMIN OPTION
GRANT "JAVAIDPRIV" TO ×userName× WITH ADMIN OPTION
GRANT "SELECT_CATALOG_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "JAVADEBUGPRIV" TO ×userName× WITH ADMIN OPTION
GRANT "CONNECT" TO ×userName× WITH ADMIN OPTION
--GRANT "ACCHK_READ" TO ×userName× WITH ADMIN OPTION
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO ×userName× WITH ADMIN OPTION
GRANT "SODA_APP" TO ×userName× WITH ADMIN OPTION
GRANT "BDSQL_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "OEM_MONITOR" TO ×userName× WITH ADMIN OPTION
GRANT "GSMADMIN_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "AQ_USER_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "JAVAUSERPRIV" TO ×userName× WITH ADMIN OPTION
GRANT "XDB_SET_INVOKER" TO ×userName× WITH ADMIN OPTION
GRANT "RECOVERY_CATALOG_OWNER" TO ×userName× WITH ADMIN OPTION
GRANT "JAVA_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DBFS_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "PDB_DBA" TO ×userName× WITH ADMIN OPTION
GRANT "RDFCTX_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO ×userName× WITH ADMIN OPTION
GRANT "CDB_DBA" TO ×userName× WITH ADMIN OPTION
GRANT "JAVASYSPRIV" TO ×userName× WITH ADMIN OPTION
GRANT "GSMROOTUSER_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "HS_ADMIN_SELECT_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "AUDIT_VIEWER" TO ×userName× WITH ADMIN OPTION
GRANT "RESOURCE" TO ×userName× WITH ADMIN OPTION
GRANT "DV_OWNER" TO ×userName× WITH ADMIN OPTION
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO ×userName× WITH ADMIN OPTION
GRANT "EXECUTE_CATALOG_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "DATAPATCH_ROLE" TO ×userName× WITH ADMIN OPTION
GRANT "DV_ACCTMGR" TO ×userName× WITH ADMIN OPTION
GRANT "EXP_FULL_DATABASE" TO ×userName× WITH ADMIN OPTION
GRANT "DBMS_MDX_INTERNAL" TO ×userName× WITH ADMIN OPTION
GRANT "DV_STREAMS_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "XS_NAMESPACE_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "BDSQL_USER" TO ×userName× WITH ADMIN OPTION
GRANT "ORDADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "AUTHENTICATEDUSER" TO ×userName× WITH ADMIN OPTION
GRANT "CAPTURE_ADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "OEM_ADVISOR" TO ×userName× WITH ADMIN OPTION
GRANT "XS_CONNECT" TO ×userName× WITH ADMIN OPTION
GRANT "XDBADMIN" TO ×userName× WITH ADMIN OPTION
GRANT "EM_EXPRESS_BASIC" TO ×userName× WITH ADMIN OPTION
ALTER USER ×userName× DEFAULT ROLE "DBA","DV_MONITOR","CTXAPP","DV_AUDIT_CLEANUP","EM_EXPRESS_ALL","WM_ADMIN_ROLE","OLAP_USER","OLAP_XS_ADMIN","DV_SECANALYST","RECOVERY_CATALOG_OWNER_VPD","XS_CACHE_ADMIN","GDS_CATALOG_SELECT","SCHEDULER_ADMIN","PROVISIONER","AUDIT_ADMIN","XDB_WEBSERVICES_OVER_HTTP","AQ_ADMINISTRATOR_ROLE","SYSUMF_ROLE","APPLICATION_TRACE_VIEWER","XDB_WEBSERVICES","LBAC_DBA","OPTIMIZER_PROCESSING_RATE","RECOVERY_CATALOG_USER","DV_DATAPUMP_NETWORK_LINK","GSMUSER_ROLE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","DBJAVASCRIPT","GSM_POOLADMIN_ROLE","DV_ADMIN","DV_POLICY_OWNER","HS_ADMIN_ROLE","XS_SESSION_ADMIN","DV_GOLDENGATE_ADMIN","IMP_FULL_DATABASE","DV_XSTREAM_ADMIN","DV_PATCH_ADMIN","GGSYS_ROLE","DATAPUMP_EXP_FULL_DATABASE","EJBCLIENT","HS_ADMIN_EXECUTE_ROLE","JMXSERVER","OLAP_DBA","ADM_PARALLEL_EXECUTE_TASK","JAVAIDPRIV","SELECT_CATALOG_ROLE","JAVADEBUGPRIV","CONNECT","DATAPUMP_IMP_FULL_DATABASE","SODA_APP","BDSQL_ADMIN","OEM_MONITOR","GSMADMIN_ROLE","AQ_USER_ROLE","JAVAUSERPRIV","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","JAVA_ADMIN","DBFS_ROLE","PDB_DBA","RDFCTX_ADMIN","DV_GOLDENGATE_REDO_ACCESS","CDB_DBA","JAVASYSPRIV","GSMROOTUSER_ROLE","HS_ADMIN_SELECT_ROLE","AUDIT_VIEWER","RESOURCE","DV_OWNER","XDB_WEBSERVICES_WITH_PUBLIC","EXECUTE_CATALOG_ROLE","DATAPATCH_ROLE","DV_ACCTMGR","EXP_FULL_DATABASE","DBMS_MDX_INTERNAL","DV_STREAMS_ADMIN","XS_NAMESPACE_ADMIN","BDSQL_USER","ORDADMIN","AUTHENTICATEDUSER","CAPTURE_ADMIN","OEM_ADVISOR","XS_CONNECT","XDBADMIN","EM_EXPRESS_BASIC"
--,"PPLB_ROLE","MAINTPLAN_APP","AVTUNE_PKG_ROLE","ACCHK_READ"
GRANT CREATE JOB TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT UPDATE ANY CUBE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY ANALYTIC VIEW TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY TRIGGER TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY SQL TRANSLATION PROFILE TO ×userName× WITH ADMIN OPTION
GRANT MANAGE ANY FILE GROUP TO ×userName× WITH ADMIN OPTION
GRANT ALTER PUBLIC DATABASE LINK TO ×userName× WITH ADMIN OPTION
GRANT MANAGE FILE GROUP TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY INDEX TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY SEQUENCE TO ×userName× WITH ADMIN OPTION
GRANT ALTER PROFILE TO ×userName× WITH ADMIN OPTION
GRANT INHERIT ANY PRIVILEGES TO ×userName× WITH ADMIN OPTION
GRANT UNDER ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY LIBRARY TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY EDITION TO ×userName× WITH ADMIN OPTION
GRANT CREATE ROLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE LIBRARY TO ×userName× WITH ADMIN OPTION
GRANT DROP ROLLBACK SEGMENT TO ×userName× WITH ADMIN OPTION
GRANT CREATE TRIGGER TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER DATABASE TRIGGER TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY OUTLINE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY ANALYTIC VIEW TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY INDEXTYPE TO ×userName× WITH ADMIN OPTION
GRANT USE ANY JOB RESOURCE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY DIRECTORY TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY RULE SET TO ×userName× WITH ADMIN OPTION
GRANT USE ANY SQL TRANSLATION PROFILE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT DEBUG CONNECT SESSION TO ×userName× WITH ADMIN OPTION
GRANT LOGMINING TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY ATTRIBUTE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT CREATE LOCKDOWN PROFILE TO ×userName× WITH ADMIN OPTION
GRANT ALTER SESSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE MATERIALIZED VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE PLUGGABLE DATABASE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY ANALYTIC VIEW TO ×userName× WITH ADMIN OPTION
GRANT WRITE ANY ANALYTIC VIEW CACHE TO ×userName× WITH ADMIN OPTION
GRANT MERGE ANY VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY INDEX TO ×userName× WITH ADMIN OPTION
GRANT READ ANY ANALYTIC VIEW CACHE TO ×userName× WITH ADMIN OPTION
GRANT CREATE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY RULE SET TO ×userName× WITH ADMIN OPTION
GRANT CREATE SQL TRANSLATION PROFILE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY MATERIALIZED VIEW TO ×userName× WITH ADMIN OPTION
GRANT AUDIT SYSTEM TO ×userName× WITH ADMIN OPTION
GRANT CREATE OPERATOR TO ×userName× WITH ADMIN OPTION
GRANT MANAGE ANY QUEUE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY SQL PROFILE TO ×userName× WITH ADMIN OPTION
GRANT GRANT ANY OBJECT PRIVILEGE TO ×userName× WITH ADMIN OPTION
GRANT CREATE INDEXTYPE TO ×userName× WITH ADMIN OPTION
GRANT AUDIT ANY TO ×userName× WITH ADMIN OPTION
GRANT INHERIT ANY REMOTE PRIVILEGES TO ×userName× WITH ADMIN OPTION
GRANT SYSKM TO ×userName× WITH ADMIN OPTION
GRANT DEBUG ANY PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY SEQUENCE TO ×userName× WITH ADMIN OPTION
GRANT CREATE MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT UPDATE ANY CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT CREATE VIEW TO ×userName× WITH ADMIN OPTION
GRANT ALTER DATABASE LINK TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY SQL TRANSLATION PROFILE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY EVALUATION CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT DELETE ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY ATTRIBUTE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE SESSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE RULE TO ×userName× WITH ADMIN OPTION
GRANT BECOME USER TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT INSERT ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY SQL PROFILE TO ×userName× WITH ADMIN OPTION
GRANT FORCE ANY TRANSACTION TO ×userName× WITH ADMIN OPTION
GRANT DELETE ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY SEQUENCE TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY EDITION TO ×userName× WITH ADMIN OPTION
GRANT CREATE EXTERNAL JOB TO ×userName× WITH ADMIN OPTION
GRANT EM EXPRESS CONNECT TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY MATERIALIZED VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT FLASHBACK ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY RULE SET TO ×userName× WITH ADMIN OPTION
GRANT BACKUP ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY CUBE TO ×userName× WITH ADMIN OPTION
GRANT CREATE CREDENTIAL TO ×userName× WITH ADMIN OPTION
GRANT CREATE TABLE TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY LIBRARY TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY OUTLINE TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY HIERARCHY TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANALYTIC VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER KEY MANAGEMENT TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY CLUSTER TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY CLASS TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CREDENTIAL TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT SYSBACKUP TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY RULE SET TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY SEQUENCE TO ×userName× WITH ADMIN OPTION
GRANT UNDER ANY TYPE TO ×userName× WITH ADMIN OPTION
GRANT MANAGE TABLESPACE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY OPERATOR TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY OPERATOR TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY HIERARCHY TO ×userName× WITH ADMIN OPTION
GRANT EXEMPT IDENTITY POLICY TO ×userName× WITH ADMIN OPTION
GRANT CREATE TYPE TO ×userName× WITH ADMIN OPTION
GRANT CREATE TABLESPACE TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY TRANSACTION TO ×userName× WITH ADMIN OPTION
GRANT DELETE ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CUBE TO ×userName× WITH ADMIN OPTION
GRANT LOCK ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE EVALUATION CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY TYPE TO ×userName× WITH ADMIN OPTION
GRANT ADVISOR TO ×userName× WITH ADMIN OPTION
GRANT CREATE PUBLIC DATABASE LINK TO ×userName× WITH ADMIN OPTION
GRANT ANALYZE ANY TO ×userName× WITH ADMIN OPTION
GRANT CREATE ATTRIBUTE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY RULE TO ×userName× WITH ADMIN OPTION
GRANT INSERT ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE ROLLBACK SEGMENT TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY JOB TO ×userName× WITH ADMIN OPTION
GRANT ALTER USER TO ×userName× WITH ADMIN OPTION
GRANT QUERY REWRITE TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY DICTIONARY TO ×userName× WITH ADMIN OPTION
GRANT CREATE PUBLIC SYNONYM TO ×userName× WITH ADMIN OPTION
--GRANT DROP LOGICAL PARTITION TRACKING TO ×userName× WITH ADMIN OPTION
GRANT GLOBAL QUERY REWRITE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY CLUSTER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY RULE TO ×userName× WITH ADMIN OPTION
GRANT UPDATE ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT SYSDBA TO ×userName× WITH ADMIN OPTION
--GRANT CREATE LOGICAL PARTITION TRACKING TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER RESOURCE MANAGER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY SYNONYM TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY SYNONYM TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT CREATE SYNONYM TO ×userName× WITH ADMIN OPTION
GRANT SET CONTAINER TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY PROGRAM TO ×userName× WITH ADMIN OPTION
GRANT EXEMPT REDACTION POLICY TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY TYPE TO ×userName× WITH ADMIN OPTION
GRANT ON COMMIT REFRESH TO ×userName× WITH ADMIN OPTION
GRANT DEBUG CONNECT ANY TO ×userName× WITH ADMIN OPTION
GRANT CREATE SEQUENCE TO ×userName× WITH ADMIN OPTION
GRANT CREATE HIERARCHY TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT COMMENT ANY MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER SQL TUNING SET TO ×userName× WITH ADMIN OPTION
GRANT SYSOPER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY INDEXTYPE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY INDEX TO ×userName× WITH ADMIN OPTION
GRANT RESTRICTED SESSION TO ×userName× WITH ADMIN OPTION
GRANT SYSDG TO ×userName× WITH ADMIN OPTION
GRANT DEQUEUE ANY QUEUE TO ×userName× WITH ADMIN OPTION
--GRANT ENABLE DIAGNOSTICS TO ×userName× WITH ADMIN OPTION
GRANT ANALYZE ANY DICTIONARY TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY INDEXTYPE TO ×userName× WITH ADMIN OPTION
GRANT TRANSLATE ANY SQL TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER ANY SQL TUNING SET TO ×userName× WITH ADMIN OPTION
GRANT CREATE USER TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY OPERATOR TO ×userName× WITH ADMIN OPTION
GRANT CREATE CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT CREATE PROFILE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY ROLE TO ×userName× WITH ADMIN OPTION
GRANT UPDATE ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY LIBRARY TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CLUSTER TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY RULE TO ×userName× WITH ADMIN OPTION
GRANT ALTER TABLESPACE TO ×userName× WITH ADMIN OPTION
GRANT UNDER ANY VIEW TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT GRANT ANY PRIVILEGE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY TRIGGER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY VIEW TO ×userName× WITH ADMIN OPTION
GRANT ALTER LOCKDOWN PROFILE TO ×userName× WITH ADMIN OPTION
GRANT EXPORT FULL DATABASE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY MEASURE FOLDER TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY EVALUATION CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT TEXT DATASTORE ACCESS TO ×userName× WITH ADMIN OPTION
GRANT FLASHBACK ARCHIVE ADMINISTER TO ×userName× WITH ADMIN OPTION
GRANT IMPORT FULL DATABASE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY OUTLINE TO ×userName× WITH ADMIN OPTION
GRANT COMMENT ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT READ ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE DATABASE LINK TO ×userName× WITH ADMIN OPTION
GRANT DROP PUBLIC SYNONYM TO ×userName× WITH ADMIN OPTION
GRANT DROP USER TO ×userName× WITH ADMIN OPTION
GRANT CHANGE NOTIFICATION TO ×userName× WITH ADMIN OPTION
GRANT CREATE MINING MODEL TO ×userName× WITH ADMIN OPTION
GRANT INSERT ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT DROP LOCKDOWN PROFILE TO ×userName× WITH ADMIN OPTION
GRANT DROP PROFILE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY MATERIALIZED VIEW TO ×userName× WITH ADMIN OPTION
GRANT CREATE RULE SET TO ×userName× WITH ADMIN OPTION
GRANT EXEMPT ACCESS POLICY TO ×userName× WITH ADMIN OPTION
GRANT MANAGE SCHEDULER TO ×userName× WITH ADMIN OPTION
GRANT READ ANY FILE GROUP TO ×userName× WITH ADMIN OPTION
GRANT FORCE TRANSACTION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY CUBE BUILD PROCESS TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY TYPE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY SQL TRANSLATION PROFILE TO ×userName× WITH ADMIN OPTION
GRANT DROP PUBLIC DATABASE LINK TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY INDEXTYPE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY SQL PROFILE TO ×userName× WITH ADMIN OPTION
--GRANT EXECUTE DYNAMIC MLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER SYSTEM TO ×userName× WITH ADMIN OPTION
GRANT UNLIMITED TABLESPACE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY ROLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY CUBE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY TRIGGER TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY DIRECTORY TO ×userName× WITH ADMIN OPTION
GRANT ENQUEUE ANY QUEUE TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY EVALUATION CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY ASSEMBLY TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY TYPE TO ×userName× WITH ADMIN OPTION
GRANT REDEFINE ANY TABLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE CLUSTER TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT EXECUTE ANY EVALUATION CONTEXT TO ×userName× WITH ADMIN OPTION
GRANT RESUMABLE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY LIBRARY TO ×userName× WITH ADMIN OPTION
GRANT DROP ANY EDITION TO ×userName× WITH ADMIN OPTION
GRANT CREATE PROCEDURE TO ×userName× WITH ADMIN OPTION
GRANT ALTER DATABASE TO ×userName× WITH ADMIN OPTION
GRANT SELECT ANY CUBE TO ×userName× WITH ADMIN OPTION
GRANT GRANT ANY ROLE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY RULE TO ×userName× WITH ADMIN OPTION
GRANT CREATE ANY ATTRIBUTE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT CREATE CUBE DIMENSION TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY OPERATOR TO ×userName× WITH ADMIN OPTION
GRANT CREATE CUBE TO ×userName× WITH ADMIN OPTION
GRANT ALTER RESOURCE COST TO ×userName× WITH ADMIN OPTION
GRANT ALTER ANY HIERARCHY TO ×userName× WITH ADMIN OPTION
GRANT DROP TABLESPACE TO ×userName× WITH ADMIN OPTION
GRANT ALTER ROLLBACK SEGMENT TO ×userName× WITH ADMIN OPTION
GRANT PURGE DBA_RECYCLEBIN TO ×userName× WITH ADMIN OPTION

alter profile DEFAULT limit PASSWORD_REUSE_TIME unlimited
alter profile DEFAULT limit PASSWORD_LIFE_TIME  unlimited
""";//@formatter:on
	}

}
